### ISSUE TITLE
Question about Laravel's ->withoutOverlapping()

### ISSUE THREAD

**Issue by volkeransmann** [jdavidbakr/MultiServerEvent#11]
Hi,

one question: does the ->withoutOverlappingMultiServer() method include the ->withoutOverlapping() functionality? Or do i have to apply both to get a task only to run on one server and also prevent from running again before finishing?

So to speak: Do i have to do: ->withoutOverlapping()->withoutOverlappingMultiServer() ?

Thanks,
volker

**Comment by jdavidbakr** [comment]
Using both would be redundant.  The withoutOverlappingMultiServer() will prevent the function from running locally a second time in the same way that it would prevent it from running on another server.
