### ISSUE TITLE
Room for potential race condition

### ISSUE THREAD

**Issue by benpoulson** [jdavidbakr/MultiServerEvent#12]
Without row-level locking, or synchronous processing you can't guarantee that two processes won't lock at the same split second.

I would consider ditching the database, and moving over to Redis/Memcached. Or at least looking into Laravel's [Pessimistic Locking](https://laravel.com/docs/5.4/queries#pessimistic-locking).

**Comment by jdavidbakr** [comment]
The way the database entry works should prevent a race condition.  The script performs an insert against a table with a unique column for the mutex, if it succeeds then it continues, if it fails it does not.  The database will prevent two processes from successfully completing the insert at the same time.
