### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by webmake** [jdavidbakr/MultiServerEvent#19]
Hello,

It seems, that package not compatible with laravel 5.6 version at all for now, there occurs an error `ReflectionException : Class Illuminate\Console\Scheduling\CacheMutex does not exist`
it seems that related with unmentioned change
https://github.com/laravel/framework/commit/ee813f990db7032d66af4d7765cb51b99a129a81#diff-6254d8c602012fd555a7b6612df661ad

but might be and other compatibility problems

**Comment by jdavidbakr** [comment]
Laravel 5.6 has a built-in replacement for this, the `onOneServer()` call.  I am going to deprecate this as of Laravel 5.5 since the functionality I'm implementing is now part of Laravel core.

**Comment by webmake** [comment]
Ok, now I see correct constrains :) thanks for reply
