### ISSUE TITLE
Laravel 5.2 support

### ISSUE THREAD

**Issue by jbardnz** [jdavidbakr/MultiServerEvent#2]
Hey

Just wondered if their are any plans for Laravel 5.2 support. If you can point me in the right direction I may be able to provide a pull request. 

Currently I get the following error when publishing the migration:
     `Call to undefined method jdavidbakr\MultiServerEvent\Commands\MultiServerMigrationService::isDeferred() in /home/vagra
  nt/Code/designerwardrobe/vendor/laravel/framework/src/Illuminate/Foundation
  /ProviderRepository.php on line 119`

**Comment by jdavidbakr** [comment]
I think you might have put the "\jdavidbakr\MultiServerEvent\Commands\MultiServerMigrationService::class," line in \config\app.php instead of in \App\Console\Kernel.php.

**Comment by jbardnz** [comment]
Hey

Yes you are indeed correct, I read through the install readme to quickly!

I have this all working correctly on 5.2.21, would it be possible to update the composer to allow installs on 5.2?

**Comment by jdavidbakr** [comment]
composer.json has been updated and new version 1.0.4 released.
