### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by DeftNerd** [jdavidbakr/MultiServerEvent#8]
Can't upgrade to Laravel 5.4 because MultiServerEvent is locked to 5.1, 5.2, and 5.3. 

I haven't changed it and tried it in production, but I looked through the code and didn't see any breaking changes that might need to be changed. Taylor made some changes to Containers (binding, make method, resolving, after resolving, and now share is removed), but all your code really does is run the container so you should be good!

**Comment by jdavidbakr** [comment]
There actually are breaking changes - just released 2.0 which is Laravel 5.4 compatible.  Note the readme as to the change in the kernel file setup.
